// 设置页共享常量与工具函数
import type { Settings } from './types';

export const emptySettings: Settings = {
  dnsServerDomain: '',
  defaultRecordTtl: '300',
  defaultNsRecordTtl: '3600',
  defaultSoaRecordTtl: '3600',
  defaultResponsiblePerson: '',
  useSoaSerialDateScheme: false,
  minSoaRefresh: '300',
  minSoaRetry: '300',
  dnsServerEnableCheckForUpdate: true,
  dnsAppsEnableAutomaticUpdate: true,
  ipv6Mode: 'Disabled',
  preferIPv6: false,
  enableUdpSocketPool: false,
  udpPayloadSize: '1232',
  dnssecValidation: false,
  eDnsClientSubnet: false,
  eDnsClientSubnetIPv4PrefixLength: '24',
  eDnsClientSubnetIPv6PrefixLength: '56',
  eDnsClientSubnetIpv4Override: '',
  eDnsClientSubnetIpv6Override: '',
  qpmLimitSampleMinutes: '1',
  qpmLimitUdpTruncationPercentage: '25',
  clientTimeout: '3000',
  tcpSendTimeout: '5000',
  tcpReceiveTimeout: '5000',
  quicIdleTimeout: '30000',
  quicMaxInboundStreams: '2000',
  listenBacklog: '512',
  udpSendBufferSizeKB: '2048',
  udpReceiveBufferSizeKB: '2048',
  maxConcurrentResolutionsPerCore: '128',
  webServiceHttpPort: '5380',
  webServiceEnableHttpUnixSocket: false,
  webServiceHttpUnixSocket: '',
  webServiceEnableTlsUnixSocket: false,
  webServiceTlsUnixSocket: '',
  webServiceEnableTls: false,
  webServiceEnableHttp3: false,
  webServiceHttpToTlsRedirect: false,
  webServiceUseSelfSignedTlsCertificate: false,
  webServiceTlsPort: '53443',
  webServiceCspFrameAncestorsHeader: "'none'",
  webServiceRealIpHeader: 'X-Forwarded-For',
  enableEDnsClientSubnetSourceAddress: false,
  enableDnsOverUdpProxy: false,
  enableDnsOverTcpProxy: false,
  enableDnsOverHttp: false,
  enableDnsOverHttpUnixSocket: false,
  enableDnsOverHttpsUnixSocket: false,
  enableDnsOverTls: false,
  enableDnsOverHttps: false,
  enableDnsOverHttp3: false,
  enableDnsOverQuic: false,
  enableDnsOverHttpHelpRedirect: true,
  dnsOverUdpProxyPort: '53',
  dnsOverTcpProxyPort: '53',
  dnsOverHttpPort: '5380',
  dnsOverHttpUnixSocket: '',
  dnsOverHttpsUnixSocket: '',
  dnsOverTlsPort: '853',
  dnsOverHttpsPort: '443',
  dnsOverQuicPort: '853',
  dnsOverHttpRealIpHeader: 'X-Forwarded-For',
  recursion: 'Deny',
  randomizeName: true,
  qnameMinimization: true,
  locallyServedDnsZones: true,
  resolverRetries: '3',
  resolverTimeout: '3000',
  resolverConcurrency: '16',
  resolverMaxStackCount: '50',
  saveCache: false,
  serveStale: false,
  serveStaleTtl: '172800',
  serveStaleAnswerTtl: '30',
  serveStaleResetTtl: '300',
  serveStaleMaxWaitTime: '3000',
  cacheMaximumEntries: '10000',
  cacheMinimumRecordTtl: '10',
  cacheMaximumRecordTtl: '172800',
  cacheNegativeRecordTtl: '300',
  cacheFailureRecordTtl: '60',
  cachePrefetchEligibility: '2',
  cachePrefetchTrigger: '0.5',
  cachePrefetchSampleIntervalInMinutes: '5',
  cachePrefetchSampleEligibilityHitsPerHour: '60',
  enableBlocking: false,
  allowTxtBlockingReport: false,
  blockingType: 'AnyAddress',
  blockingAnswerTtl: '60',
  blockListUpdateIntervalHours: '24',
  forwarderProtocol: 'Udp',
  concurrentForwarding: false,
  forwarderRetries: '2',
  forwarderTimeout: '3000',
  forwarderConcurrency: '16',
  loggingType: 'None',
  ignoreResolverLogs: false,
  logQueries: false,
  noStackTrace: false,
  useLocalTime: false,
  logFolder: 'logs',
  maxLogFileDays: '30',
  enableInMemoryStats: false,
  maxStatFileDays: '3650',
};

// 数组 → 多行文本
export const toList = (v?: string[]): string => (v || []).join('\n');

// 多行文本 → 逗号分隔（trim + 去空行）
export const toArray = (text: string): string =>
  text
    .split('\n')
    .map(x => x.trim())
    .filter(x => x !== '')
    .join(',');
