// DNS 客户端页常量

export const DNS_RECORD_TYPES = [
  'A',
  'NS',
  'CNAME',
  'SOA',
  'PTR',
  'MX',
  'TXT',
  'RP',
  'AAAA',
  'SRV',
  'NAPTR',
  'DNAME',
  'DS',
  'SSHFP',
  'RRSIG',
  'NSEC',
  'DNSKEY',
  'NSEC3',
  'NSEC3PARAM',
  'TLSA',
  'ZONEMD',
  'SVCB',
  'HTTPS',
  'URI',
  'CAA',
  'ANY',
  'AXFR',
  'ANAME',
];

export const DNS_PROTOCOLS = ['UDP', 'TCP', 'TLS', 'HTTPS', 'QUIC'];

// 表格内 dot Badge 固定 body 背景，避免行 hover 高亮时 badge 融入行背景
export const DOT_BADGE_STYLE = { backgroundColor: 'var(--mantine-color-body)' };

export const RECORD_TYPE_COLORS: Record<string, string> = {
  A: 'blue',
  AAAA: 'blue',
  NS: 'green',
  CNAME: 'violet',
  MX: 'orange',
  TXT: 'teal',
  SOA: 'red',
  SRV: 'pink',
  PTR: 'cyan',
  CAA: 'grape',
  DS: 'indigo',
  SSHFP: 'indigo',
  TLSA: 'indigo',
  HTTPS: 'yellow',
  SVCB: 'yellow',
  DNAME: 'violet',
  RP: 'orange',
  NAPTR: 'pink',
  DNSKEY: 'dark',
  RRSIG: 'dark',
  NSEC: 'dark',
  NSEC3: 'dark',
  NSEC3PARAM: 'dark',
  URI: 'yellow',
  ANAME: 'violet',
  FWD: 'teal',
  APP: 'grape',
  ZONEMD: 'dark',
  OPT: 'gray',
};
