/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedZonesRouteImport } from './routes/_authenticated/zones'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedDnsClientRouteImport } from './routes/_authenticated/dns-client'
import { Route as AuthenticatedDhcpRouteImport } from './routes/_authenticated/dhcp'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCacheRouteImport } from './routes/_authenticated/cache'
import { Route as AuthenticatedBlockedRouteImport } from './routes/_authenticated/blocked'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedAllowedRouteImport } from './routes/_authenticated/allowed'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedLogsIndexRouteImport } from './routes/_authenticated/logs.index'
import { Route as AuthenticatedDhcpIndexRouteImport } from './routes/_authenticated/dhcp.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSettingsWebServiceRouteImport } from './routes/_authenticated/settings.webService'
import { Route as AuthenticatedSettingsTsigRouteImport } from './routes/_authenticated/settings.tsig'
import { Route as AuthenticatedSettingsRecursionRouteImport } from './routes/_authenticated/settings.recursion'
import { Route as AuthenticatedSettingsProxyForwardersRouteImport } from './routes/_authenticated/settings.proxyForwarders'
import { Route as AuthenticatedSettingsOptionalProtocolsRouteImport } from './routes/_authenticated/settings.optionalProtocols'
import { Route as AuthenticatedSettingsLoggingRouteImport } from './routes/_authenticated/settings.logging'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings.general'
import { Route as AuthenticatedSettingsCacheRouteImport } from './routes/_authenticated/settings.cache'
import { Route as AuthenticatedSettingsBlockingRouteImport } from './routes/_authenticated/settings.blocking'
import { Route as AuthenticatedLogsViewRouteImport } from './routes/_authenticated/logs.view'
import { Route as AuthenticatedLogsQueryRouteImport } from './routes/_authenticated/logs.query'
import { Route as AuthenticatedDhcpScopesRouteImport } from './routes/_authenticated/dhcp.scopes'
import { Route as AuthenticatedDhcpLeasesRouteImport } from './routes/_authenticated/dhcp.leases'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSsoRouteImport } from './routes/_authenticated/admin.sso'
import { Route as AuthenticatedAdminSessionsRouteImport } from './routes/_authenticated/admin.sessions'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin.permissions'
import { Route as AuthenticatedAdminGroupsRouteImport } from './routes/_authenticated/admin.groups'
import { Route as AuthenticatedAdminClusterRouteImport } from './routes/_authenticated/admin.cluster'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedZonesRoute = AuthenticatedZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDnsClientRoute = AuthenticatedDnsClientRouteImport.update({
  id: '/dns-client',
  path: '/dns-client',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDhcpRoute = AuthenticatedDhcpRouteImport.update({
  id: '/dhcp',
  path: '/dhcp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCacheRoute = AuthenticatedCacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBlockedRoute = AuthenticatedBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAllowedRoute = AuthenticatedAllowedRouteImport.update({
  id: '/allowed',
  path: '/allowed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLogsIndexRoute = AuthenticatedLogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLogsRoute,
} as any)
const AuthenticatedDhcpIndexRoute = AuthenticatedDhcpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDhcpRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSettingsWebServiceRoute =
  AuthenticatedSettingsWebServiceRouteImport.update({
    id: '/webService',
    path: '/webService',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTsigRoute =
  AuthenticatedSettingsTsigRouteImport.update({
    id: '/tsig',
    path: '/tsig',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsRecursionRoute =
  AuthenticatedSettingsRecursionRouteImport.update({
    id: '/recursion',
    path: '/recursion',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProxyForwardersRoute =
  AuthenticatedSettingsProxyForwardersRouteImport.update({
    id: '/proxyForwarders',
    path: '/proxyForwarders',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsOptionalProtocolsRoute =
  AuthenticatedSettingsOptionalProtocolsRouteImport.update({
    id: '/optionalProtocols',
    path: '/optionalProtocols',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLoggingRoute =
  AuthenticatedSettingsLoggingRouteImport.update({
    id: '/logging',
    path: '/logging',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCacheRoute =
  AuthenticatedSettingsCacheRouteImport.update({
    id: '/cache',
    path: '/cache',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBlockingRoute =
  AuthenticatedSettingsBlockingRouteImport.update({
    id: '/blocking',
    path: '/blocking',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedLogsViewRoute = AuthenticatedLogsViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => AuthenticatedLogsRoute,
} as any)
const AuthenticatedLogsQueryRoute = AuthenticatedLogsQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => AuthenticatedLogsRoute,
} as any)
const AuthenticatedDhcpScopesRoute = AuthenticatedDhcpScopesRouteImport.update({
  id: '/scopes',
  path: '/scopes',
  getParentRoute: () => AuthenticatedDhcpRoute,
} as any)
const AuthenticatedDhcpLeasesRoute = AuthenticatedDhcpLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AuthenticatedDhcpRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSsoRoute = AuthenticatedAdminSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSessionsRoute =
  AuthenticatedAdminSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGroupsRoute =
  AuthenticatedAdminGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClusterRoute =
  AuthenticatedAdminClusterRouteImport.update({
    id: '/cluster',
    path: '/cluster',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/allowed': typeof AuthenticatedAllowedRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/cache': typeof AuthenticatedCacheRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dhcp': typeof AuthenticatedDhcpRouteWithChildren
  '/dns-client': typeof AuthenticatedDnsClientRoute
  '/logs': typeof AuthenticatedLogsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/zones': typeof AuthenticatedZonesRoute
  '/admin/cluster': typeof AuthenticatedAdminClusterRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/sso': typeof AuthenticatedAdminSsoRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dhcp/leases': typeof AuthenticatedDhcpLeasesRoute
  '/dhcp/scopes': typeof AuthenticatedDhcpScopesRoute
  '/logs/query': typeof AuthenticatedLogsQueryRoute
  '/logs/view': typeof AuthenticatedLogsViewRoute
  '/settings/blocking': typeof AuthenticatedSettingsBlockingRoute
  '/settings/cache': typeof AuthenticatedSettingsCacheRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/logging': typeof AuthenticatedSettingsLoggingRoute
  '/settings/optionalProtocols': typeof AuthenticatedSettingsOptionalProtocolsRoute
  '/settings/proxyForwarders': typeof AuthenticatedSettingsProxyForwardersRoute
  '/settings/recursion': typeof AuthenticatedSettingsRecursionRoute
  '/settings/tsig': typeof AuthenticatedSettingsTsigRoute
  '/settings/webService': typeof AuthenticatedSettingsWebServiceRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dhcp/': typeof AuthenticatedDhcpIndexRoute
  '/logs/': typeof AuthenticatedLogsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AuthenticatedAboutRoute
  '/allowed': typeof AuthenticatedAllowedRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/cache': typeof AuthenticatedCacheRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dns-client': typeof AuthenticatedDnsClientRoute
  '/zones': typeof AuthenticatedZonesRoute
  '/admin/cluster': typeof AuthenticatedAdminClusterRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/sso': typeof AuthenticatedAdminSsoRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dhcp/leases': typeof AuthenticatedDhcpLeasesRoute
  '/dhcp/scopes': typeof AuthenticatedDhcpScopesRoute
  '/logs/query': typeof AuthenticatedLogsQueryRoute
  '/logs/view': typeof AuthenticatedLogsViewRoute
  '/settings/blocking': typeof AuthenticatedSettingsBlockingRoute
  '/settings/cache': typeof AuthenticatedSettingsCacheRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/logging': typeof AuthenticatedSettingsLoggingRoute
  '/settings/optionalProtocols': typeof AuthenticatedSettingsOptionalProtocolsRoute
  '/settings/proxyForwarders': typeof AuthenticatedSettingsProxyForwardersRoute
  '/settings/recursion': typeof AuthenticatedSettingsRecursionRoute
  '/settings/tsig': typeof AuthenticatedSettingsTsigRoute
  '/settings/webService': typeof AuthenticatedSettingsWebServiceRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dhcp': typeof AuthenticatedDhcpIndexRoute
  '/logs': typeof AuthenticatedLogsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/allowed': typeof AuthenticatedAllowedRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRoute
  '/_authenticated/blocked': typeof AuthenticatedBlockedRoute
  '/_authenticated/cache': typeof AuthenticatedCacheRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dhcp': typeof AuthenticatedDhcpRouteWithChildren
  '/_authenticated/dns-client': typeof AuthenticatedDnsClientRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/zones': typeof AuthenticatedZonesRoute
  '/_authenticated/admin/cluster': typeof AuthenticatedAdminClusterRoute
  '/_authenticated/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/_authenticated/admin/sso': typeof AuthenticatedAdminSsoRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/dhcp/leases': typeof AuthenticatedDhcpLeasesRoute
  '/_authenticated/dhcp/scopes': typeof AuthenticatedDhcpScopesRoute
  '/_authenticated/logs/query': typeof AuthenticatedLogsQueryRoute
  '/_authenticated/logs/view': typeof AuthenticatedLogsViewRoute
  '/_authenticated/settings/blocking': typeof AuthenticatedSettingsBlockingRoute
  '/_authenticated/settings/cache': typeof AuthenticatedSettingsCacheRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/logging': typeof AuthenticatedSettingsLoggingRoute
  '/_authenticated/settings/optionalProtocols': typeof AuthenticatedSettingsOptionalProtocolsRoute
  '/_authenticated/settings/proxyForwarders': typeof AuthenticatedSettingsProxyForwardersRoute
  '/_authenticated/settings/recursion': typeof AuthenticatedSettingsRecursionRoute
  '/_authenticated/settings/tsig': typeof AuthenticatedSettingsTsigRoute
  '/_authenticated/settings/webService': typeof AuthenticatedSettingsWebServiceRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dhcp/': typeof AuthenticatedDhcpIndexRoute
  '/_authenticated/logs/': typeof AuthenticatedLogsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/admin'
    | '/allowed'
    | '/apps'
    | '/blocked'
    | '/cache'
    | '/dashboard'
    | '/dhcp'
    | '/dns-client'
    | '/logs'
    | '/settings'
    | '/zones'
    | '/admin/cluster'
    | '/admin/groups'
    | '/admin/permissions'
    | '/admin/sessions'
    | '/admin/sso'
    | '/admin/users'
    | '/dhcp/leases'
    | '/dhcp/scopes'
    | '/logs/query'
    | '/logs/view'
    | '/settings/blocking'
    | '/settings/cache'
    | '/settings/general'
    | '/settings/logging'
    | '/settings/optionalProtocols'
    | '/settings/proxyForwarders'
    | '/settings/recursion'
    | '/settings/tsig'
    | '/settings/webService'
    | '/admin/'
    | '/dhcp/'
    | '/logs/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/about'
    | '/allowed'
    | '/apps'
    | '/blocked'
    | '/cache'
    | '/dashboard'
    | '/dns-client'
    | '/zones'
    | '/admin/cluster'
    | '/admin/groups'
    | '/admin/permissions'
    | '/admin/sessions'
    | '/admin/sso'
    | '/admin/users'
    | '/dhcp/leases'
    | '/dhcp/scopes'
    | '/logs/query'
    | '/logs/view'
    | '/settings/blocking'
    | '/settings/cache'
    | '/settings/general'
    | '/settings/logging'
    | '/settings/optionalProtocols'
    | '/settings/proxyForwarders'
    | '/settings/recursion'
    | '/settings/tsig'
    | '/settings/webService'
    | '/admin'
    | '/dhcp'
    | '/logs'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/about'
    | '/_authenticated/admin'
    | '/_authenticated/allowed'
    | '/_authenticated/apps'
    | '/_authenticated/blocked'
    | '/_authenticated/cache'
    | '/_authenticated/dashboard'
    | '/_authenticated/dhcp'
    | '/_authenticated/dns-client'
    | '/_authenticated/logs'
    | '/_authenticated/settings'
    | '/_authenticated/zones'
    | '/_authenticated/admin/cluster'
    | '/_authenticated/admin/groups'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/sessions'
    | '/_authenticated/admin/sso'
    | '/_authenticated/admin/users'
    | '/_authenticated/dhcp/leases'
    | '/_authenticated/dhcp/scopes'
    | '/_authenticated/logs/query'
    | '/_authenticated/logs/view'
    | '/_authenticated/settings/blocking'
    | '/_authenticated/settings/cache'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/logging'
    | '/_authenticated/settings/optionalProtocols'
    | '/_authenticated/settings/proxyForwarders'
    | '/_authenticated/settings/recursion'
    | '/_authenticated/settings/tsig'
    | '/_authenticated/settings/webService'
    | '/_authenticated/admin/'
    | '/_authenticated/dhcp/'
    | '/_authenticated/logs/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/zones': {
      id: '/_authenticated/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof AuthenticatedZonesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dns-client': {
      id: '/_authenticated/dns-client'
      path: '/dns-client'
      fullPath: '/dns-client'
      preLoaderRoute: typeof AuthenticatedDnsClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dhcp': {
      id: '/_authenticated/dhcp'
      path: '/dhcp'
      fullPath: '/dhcp'
      preLoaderRoute: typeof AuthenticatedDhcpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cache': {
      id: '/_authenticated/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof AuthenticatedCacheRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blocked': {
      id: '/_authenticated/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof AuthenticatedBlockedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/allowed': {
      id: '/_authenticated/allowed'
      path: '/allowed'
      fullPath: '/allowed'
      preLoaderRoute: typeof AuthenticatedAllowedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/logs/': {
      id: '/_authenticated/logs/'
      path: '/'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthenticatedLogsIndexRouteImport
      parentRoute: typeof AuthenticatedLogsRoute
    }
    '/_authenticated/dhcp/': {
      id: '/_authenticated/dhcp/'
      path: '/'
      fullPath: '/dhcp/'
      preLoaderRoute: typeof AuthenticatedDhcpIndexRouteImport
      parentRoute: typeof AuthenticatedDhcpRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/settings/webService': {
      id: '/_authenticated/settings/webService'
      path: '/webService'
      fullPath: '/settings/webService'
      preLoaderRoute: typeof AuthenticatedSettingsWebServiceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/tsig': {
      id: '/_authenticated/settings/tsig'
      path: '/tsig'
      fullPath: '/settings/tsig'
      preLoaderRoute: typeof AuthenticatedSettingsTsigRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/recursion': {
      id: '/_authenticated/settings/recursion'
      path: '/recursion'
      fullPath: '/settings/recursion'
      preLoaderRoute: typeof AuthenticatedSettingsRecursionRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/proxyForwarders': {
      id: '/_authenticated/settings/proxyForwarders'
      path: '/proxyForwarders'
      fullPath: '/settings/proxyForwarders'
      preLoaderRoute: typeof AuthenticatedSettingsProxyForwardersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/optionalProtocols': {
      id: '/_authenticated/settings/optionalProtocols'
      path: '/optionalProtocols'
      fullPath: '/settings/optionalProtocols'
      preLoaderRoute: typeof AuthenticatedSettingsOptionalProtocolsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/logging': {
      id: '/_authenticated/settings/logging'
      path: '/logging'
      fullPath: '/settings/logging'
      preLoaderRoute: typeof AuthenticatedSettingsLoggingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/cache': {
      id: '/_authenticated/settings/cache'
      path: '/cache'
      fullPath: '/settings/cache'
      preLoaderRoute: typeof AuthenticatedSettingsCacheRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/blocking': {
      id: '/_authenticated/settings/blocking'
      path: '/blocking'
      fullPath: '/settings/blocking'
      preLoaderRoute: typeof AuthenticatedSettingsBlockingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/logs/view': {
      id: '/_authenticated/logs/view'
      path: '/view'
      fullPath: '/logs/view'
      preLoaderRoute: typeof AuthenticatedLogsViewRouteImport
      parentRoute: typeof AuthenticatedLogsRoute
    }
    '/_authenticated/logs/query': {
      id: '/_authenticated/logs/query'
      path: '/query'
      fullPath: '/logs/query'
      preLoaderRoute: typeof AuthenticatedLogsQueryRouteImport
      parentRoute: typeof AuthenticatedLogsRoute
    }
    '/_authenticated/dhcp/scopes': {
      id: '/_authenticated/dhcp/scopes'
      path: '/scopes'
      fullPath: '/dhcp/scopes'
      preLoaderRoute: typeof AuthenticatedDhcpScopesRouteImport
      parentRoute: typeof AuthenticatedDhcpRoute
    }
    '/_authenticated/dhcp/leases': {
      id: '/_authenticated/dhcp/leases'
      path: '/leases'
      fullPath: '/dhcp/leases'
      preLoaderRoute: typeof AuthenticatedDhcpLeasesRouteImport
      parentRoute: typeof AuthenticatedDhcpRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sso': {
      id: '/_authenticated/admin/sso'
      path: '/sso'
      fullPath: '/admin/sso'
      preLoaderRoute: typeof AuthenticatedAdminSsoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sessions': {
      id: '/_authenticated/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AuthenticatedAdminSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/groups': {
      id: '/_authenticated/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthenticatedAdminGroupsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cluster': {
      id: '/_authenticated/admin/cluster'
      path: '/cluster'
      fullPath: '/admin/cluster'
      preLoaderRoute: typeof AuthenticatedAdminClusterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClusterRoute: typeof AuthenticatedAdminClusterRoute
  AuthenticatedAdminGroupsRoute: typeof AuthenticatedAdminGroupsRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminSessionsRoute: typeof AuthenticatedAdminSessionsRoute
  AuthenticatedAdminSsoRoute: typeof AuthenticatedAdminSsoRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClusterRoute: AuthenticatedAdminClusterRoute,
  AuthenticatedAdminGroupsRoute: AuthenticatedAdminGroupsRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminSessionsRoute: AuthenticatedAdminSessionsRoute,
  AuthenticatedAdminSsoRoute: AuthenticatedAdminSsoRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDhcpRouteChildren {
  AuthenticatedDhcpLeasesRoute: typeof AuthenticatedDhcpLeasesRoute
  AuthenticatedDhcpScopesRoute: typeof AuthenticatedDhcpScopesRoute
  AuthenticatedDhcpIndexRoute: typeof AuthenticatedDhcpIndexRoute
}

const AuthenticatedDhcpRouteChildren: AuthenticatedDhcpRouteChildren = {
  AuthenticatedDhcpLeasesRoute: AuthenticatedDhcpLeasesRoute,
  AuthenticatedDhcpScopesRoute: AuthenticatedDhcpScopesRoute,
  AuthenticatedDhcpIndexRoute: AuthenticatedDhcpIndexRoute,
}

const AuthenticatedDhcpRouteWithChildren =
  AuthenticatedDhcpRoute._addFileChildren(AuthenticatedDhcpRouteChildren)

interface AuthenticatedLogsRouteChildren {
  AuthenticatedLogsQueryRoute: typeof AuthenticatedLogsQueryRoute
  AuthenticatedLogsViewRoute: typeof AuthenticatedLogsViewRoute
  AuthenticatedLogsIndexRoute: typeof AuthenticatedLogsIndexRoute
}

const AuthenticatedLogsRouteChildren: AuthenticatedLogsRouteChildren = {
  AuthenticatedLogsQueryRoute: AuthenticatedLogsQueryRoute,
  AuthenticatedLogsViewRoute: AuthenticatedLogsViewRoute,
  AuthenticatedLogsIndexRoute: AuthenticatedLogsIndexRoute,
}

const AuthenticatedLogsRouteWithChildren =
  AuthenticatedLogsRoute._addFileChildren(AuthenticatedLogsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBlockingRoute: typeof AuthenticatedSettingsBlockingRoute
  AuthenticatedSettingsCacheRoute: typeof AuthenticatedSettingsCacheRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsLoggingRoute: typeof AuthenticatedSettingsLoggingRoute
  AuthenticatedSettingsOptionalProtocolsRoute: typeof AuthenticatedSettingsOptionalProtocolsRoute
  AuthenticatedSettingsProxyForwardersRoute: typeof AuthenticatedSettingsProxyForwardersRoute
  AuthenticatedSettingsRecursionRoute: typeof AuthenticatedSettingsRecursionRoute
  AuthenticatedSettingsTsigRoute: typeof AuthenticatedSettingsTsigRoute
  AuthenticatedSettingsWebServiceRoute: typeof AuthenticatedSettingsWebServiceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBlockingRoute: AuthenticatedSettingsBlockingRoute,
  AuthenticatedSettingsCacheRoute: AuthenticatedSettingsCacheRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsLoggingRoute: AuthenticatedSettingsLoggingRoute,
  AuthenticatedSettingsOptionalProtocolsRoute:
    AuthenticatedSettingsOptionalProtocolsRoute,
  AuthenticatedSettingsProxyForwardersRoute:
    AuthenticatedSettingsProxyForwardersRoute,
  AuthenticatedSettingsRecursionRoute: AuthenticatedSettingsRecursionRoute,
  AuthenticatedSettingsTsigRoute: AuthenticatedSettingsTsigRoute,
  AuthenticatedSettingsWebServiceRoute: AuthenticatedSettingsWebServiceRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAllowedRoute: typeof AuthenticatedAllowedRoute
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRoute
  AuthenticatedBlockedRoute: typeof AuthenticatedBlockedRoute
  AuthenticatedCacheRoute: typeof AuthenticatedCacheRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDhcpRoute: typeof AuthenticatedDhcpRouteWithChildren
  AuthenticatedDnsClientRoute: typeof AuthenticatedDnsClientRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedZonesRoute: typeof AuthenticatedZonesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAllowedRoute: AuthenticatedAllowedRoute,
  AuthenticatedAppsRoute: AuthenticatedAppsRoute,
  AuthenticatedBlockedRoute: AuthenticatedBlockedRoute,
  AuthenticatedCacheRoute: AuthenticatedCacheRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDhcpRoute: AuthenticatedDhcpRouteWithChildren,
  AuthenticatedDnsClientRoute: AuthenticatedDnsClientRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedZonesRoute: AuthenticatedZonesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
